on: pull_request
name: PR
jobs:
    CLIENT:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            - name: npm i
              working-directory: client
              run: |
                  npm install
            - name: lint
              working-directory: client
              run: |
                  npm run lint:ci
            - name: test
              working-directory: client
              run: |
                  npm run test
            - name: build
              working-directory: client
              run: |
                  npm run build:ci
    SERVER:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: psf/black@stable
